### ISSUE TITLE
Example of stat API routes give errors

### ISSUE THREAD

**Issue by jamesscottbrown** [ScottishCovidResponse/rampvis-api#4]
The example URLs listed in the README:

* `http://vis.scrc.uk/stat/v1/correlation/?var1=scotland/hospital_confirmed&var2=scotland/hospital_confirmed&metrics=zncc,pearsonr,f-test&smooth=hanning`
* `http://vis.scrc.uk/stat/v1/correlation_dynamic/?var1=scotland/hospital_confirmed&var2=scotland/hospital_confirmed&metrics=zncc,pearsonr,f-test`

throw errors:

![FileNotFoundError](https://user-images.githubusercontent.com/338833/88857926-0cc75380-d1ef-11ea-8843-2ec27894dd1d.png)

The publicly-accessibe production instance on `http://vis.scrc.uk` should probably also not be displaying stack traces like this.

**Comment by saifulkhan** [comment]
Fixed.
